version: '3.8'

services:
  mission-control-portfolio:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
